name: "Dalfox XSS Scanner (Parallel)"

on:
  workflow_dispatch:
    inputs:
      target_name:
        description: 'Name of target folder in storage repo'
        required: true
      storage_repo:
        description: 'SSH URL of scan-results-storage repo'
        required: true
      custom_cookie:
        description: 'Optional: Custom Cookie header'
        required: false
        default: ''
      custom_header:
        description: 'Optional: Custom extra header'
        required: false
        default: ''

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      chunks: ${{ steps.split.outputs.chunks }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Setup SSH
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Storage Repo
        run: git clone ${{ github.event.inputs.storage_repo }} storage_repo_clone

      - name: Split URL list into chunks
        id: split
        run: |
          URL_FILE_PATH="storage_repo_clone/${{ github.event.inputs.target_name }}/discovery/live-urls.txt"
          if [ ! -f "$URL_FILE_PATH" ]; then
            echo "URL file not found: $URL_FILE_PATH"
            exit 1
          fi
          mkdir -p url_chunks
          # Split the file into chunks of 50 lines each
          split -l 50 "$URL_FILE_PATH" url_chunks/urls_
          # Create a JSON array of the chunk filenames
          chunks=$(ls url_chunks | jq -R . | jq -s .)
          echo "chunks=$chunks" >> $GITHUB_OUTPUT

      - name: Upload chunks as artifact
        uses: actions/upload-artifact@v4
        with:
          name: url-chunks
          path: url_chunks/

  parallel-scan:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.setup.outputs.chunks) }}
      fail-fast: false

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Download URL chunks
        uses: actions/download-artifact@v4
        with:
          name: url-chunks
          path: url_chunks/

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install Dalfox
        run: go install github.com/hahwul/dalfox/v2@latest

      - name: Run Dalfox Scan on chunk
        id: dalfox
        run: |
          set -e
          CHUNK_FILE="url_chunks/${{ matrix.chunk }}"
          OUTPUT_FILE="dalfox-output-${{ matrix.chunk }}"
          PAYLOAD_FILE="dalfox_payload.txt"
          BLIND_XSS_URL="https://1.bigdav.ir/dalfox-${{ github.event.inputs.target_name }}"

          echo "Starting Dalfox scan on chunk: ${{ matrix.chunk }}"

          HEADER_ARGS=()
          if [[ -n "${{ github.event.inputs.custom_cookie }}" ]]; then
            HEADER_ARGS+=(-H "Cookie: ${{ github.event.inputs.custom_cookie }}")
          fi
          if [[ -n "${{ github.event.inputs.custom_header }}" ]]; then
            HEADER_ARGS+=(-H "${{ github.event.inputs.custom_header }}")
          fi

          $HOME/go/bin/dalfox file "$CHUNK_FILE" \
            --custom-payload "$PAYLOAD_FILE" \
            --only-custom-payload \
            -b "$BLIND_XSS_URL" \
            --silence \
            --skip-headless \
            -w 25 \
            -o "$OUTPUT_FILE" \
            "${HEADER_ARGS[@]}"

          echo "Dalfox scan complete for chunk: ${{ matrix.chunk }}. Output saved to $OUTPUT_FILE"
          echo "::set-output name=output_file::$OUTPUT_FILE"

      - name: Push results to storage repo
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          STORAGE_REPO: ${{ github.event.inputs.storage_repo }}
        run: |
          set -e
          git clone "$STORAGE_REPO" storage_repo_clone
          cd storage_repo_clone

          TARGET_DIR="${{ github.event.inputs.target_name }}/xss"
          mkdir -p "$TARGET_DIR"

          RESULT_FILE_NAME="dalfox-results-${{ matrix.chunk }}"
          mv "../${{ steps.dalfox.outputs.output_file }}" "$TARGET_DIR/$RESULT_FILE_NAME"

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .

          if ! git diff --staged --quiet; then
            git commit -m "Add Dalfox scan results for ${{ github.event.inputs.target_name }} (chunk ${{ matrix.chunk }})"
            # Retry push on failure
            for i in {1..3}; do git push && break || sleep 5; done
          else
            echo "No changes to commit for chunk ${{ matrix.chunk }}"
          fi
